kind: Secret
apiVersion: v1
metadata:
  name: template-api-d
  namespace: lab-arq-d
stringData:
  dbconfig_connectionstring : Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=bcodes-scan)(PORT=1470)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=svc_bcodes)));User Id=USR_AUT;Password=ig9RKGOQRTKzVxbWYjPLMwPkaysNA0xzhyy0PTPJpxn4gRqHdYQd/fPqOIwalmbiFlxlS359E920DTMiI80dv5wNvv4hVUChjcpZPAFmjoB+DLEyuDs3Lj1Z5oGsSsQbGCx1iKY68hUmf61nzghC1eM7SWRVGYoekz8SY166cIvZTh2KlGosX40+XgZ6B6EfYwRQt4Yp4v0YhBABFx/hFc2nunWZqT8HTbH7OweuChNNh+hdXdVQltOrqrSzJdEPeTFT0M2scdK2CGJgxjab3km5ZLiJrqZGpnBlonzq1VAjz/05XnxLjWRh0TVhOSEGYkjMEbPxzgrkNxVRXyundw==;
type: Opaque
